### ISSUE TITLE
When enabled, it overwrites Control Panel date locale setting with en-us

### ISSUE THREAD

**Issue by juresrpcic** [lindseydiloreto/craft-matrixcolors#11]
Discovered this when chasing an issue on Craft CMS issue tracker - all details here: https://github.com/craftcms/cms/issues/2439

**Comment by lindseydiloreto** [comment]
Huh, weird. I'll take a look, and let you know what I find.

**Comment by lindseydiloreto** [comment]
Looks like this might be a Craft bug after all. I've updated the other thread with some steps to reproduce.

**Comment by lindseydiloreto** [comment]
Sounds like this has been fixed for the next release of Craft! 👍 

https://github.com/craftcms/cms/issues/2439#issuecomment-366400331
