### ISSUE TITLE
Support for Neo field

### ISSUE THREAD

**Issue by jlcharette** [lindseydiloreto/craft-matrixcolors#13]
Hey there, this plugin looks awesome but does not seem to work with Neo field. It would be nice if it did!

**Comment by lindseydiloreto** [comment]
I agree!

Not sure how soon I'll get to it. Pull requests are welcome! 🙂

**Comment by ttempleton** [comment]
I'm interested in working on a pull request for this - just wondering if it would be preferred for Matrix and Neo block types to share a settings table or for each to have their own?

**Comment by lindseydiloreto** [comment]
Great, thanks @ttempleton!

It's probably preferable for them to share a settings table, unless you anticipate some sort of conflict?

**Comment by ttempleton** [comment]
Thanks @lindseydiloreto - will proceed with them sharing the settings table, there shouldn't be a conflict.

**Comment by lindseydiloreto** [comment]
Excellent, thanks @ttempleton! Looking forward to the PR. 👍

**Comment by lindseydiloreto** [comment]
Neo support has been added in **v3.0.0**.

Thanks to @ttempleton for making this a reality! 🎉
