### ISSUE TITLE
Feature request: Allow comma-seperated handles

### ISSUE THREAD

**Issue by dueddel** [lindseydiloreto/craft-matrixcolors#7]
Hi,

first of all: Nice plugin. To get colored matrix blocks is a pretty simple feature, but with great impact.
I use matrix blocks for website modules, for instance (such as a teaser tile, a newsletter subscription module etc.) and colored blocks are very helpful to keep the overview of all added modules.

Well, in my current case I have different modules that are similar. Therefore I would add all of these modules (respectively the handles of the matrix blocks) one by one to your plugin's settings and set the color for each.

Example:

| Block Type Handle     | CSS Background Color          |
|----------|-------------------|
| module1    | #c0ffee            |
| module2    | #c0ffee            |
| module3    | #c0ffee            |
| module4    | green            |
| module5    | green            |

To make this even easier I would like to add only one single color setting for multiple blocks at once. Let's say with comma-separated matrix block handles. Like so:

| Block Type Handle     | CSS Background Color          |
|----------|-------------------|
| module1, module2, module3    | #c0ffee            |
| module4, module5    | green            |

Would be awesome to have this feature. Would you mind adding that in near future? Thanks in advance for your reply.

**Comment by lindseydiloreto** [comment]
Great suggestion, and thanks for the PR!

**Comment by dueddel** [comment]
Nothing to thank for. Did it in my own interest… 💃 😉
