### ISSUE TITLE
Feature request - Color entire matrix fields

### ISSUE THREAD

**Issue by bdielman** [lindseydiloreto/craft-matrixcolors#9]
We have a site with a lot of different matrix fields (content, carousels, testimonials, etc.). There could be four or five of these fields per entry with many blocks per field, so to have the fields themselves color-coded to show that the blocks within are all part of the same group would be incredibly useful.

**Comment by lindseydiloreto** [comment]
Not entirely sure I follow... Are you saying that you want all blocks of a field to be the same color? And each Matrix field will have all of its blocks be a single color?

**Comment by bdielman** [comment]
Right. Here's a screenshot of one of the entries in question. Each section, or matrix field, could have its own color.
![matrix-fields](https://cloud.githubusercontent.com/assets/94547/17637336/f7c70a56-60b0-11e6-9b75-6aa3f8d8bb96.jpg)

**Comment by lindseydiloreto** [comment]
Hmm... I really can't think of an easy way to modify the plugin to make that possible.

Here are my suggestions for a workaround:

(1) Give your blocks more unique handles (`primaryContentText`, `secondaryContentText`). The block _names_ could remain the same, as long as the _handles_ were adjusted. You can then group your handles together, and [assign them the same color simultaneously](https://github.com/lindseydiloreto/craft-matrixcolors/issues/7).

(2) Fork this plugin, and make that adjustment yourself. If you manage to pull it off, I'd be happy to look at what you've done, and consider rolling it into the original plugin.

**Comment by bdielman** [comment]
Thanks! I'll go with option one. I haven't attempted plugin development but this could be a good excuse to start. 😀

**Comment by lindseydiloreto** [comment]
Sounds great! :)
